#Constants
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PADDLE_WIDTH = 20
PADDLE_HEIGHT = 200
PADDLE_COLOR = "white"
PADDLE_VELOCITY = 5
PADDLE_CENTER_POS = (SCREEN_HEIGHT / 2) - (PADDLE_HEIGHT / 2)
PLAYER_LEFT_POS = 10
COMPUTER_LEFT_POS = SCREEN_WIDTH - PADDLE_WIDTH - PLAYER_LEFT_POS
BALL_COLOR = "white"
BALL_WIDTH = 20
BALL_HEIGHT = 20
BALLX = int(SCREEN_WIDTH / 2)
BALLY = int(SCREEN_HEIGHT / 2)
BALL_BORDER = 8
RADIUS = 12
BALL_VELOCITY = 8

