#Constants
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PADDLE_WIDTH = 40
PADDLE_HEIGHT = 200
PADDLE_COLOR = "white"
BALL_COLOR = "white"
BALLX = int(SCREEN_WIDTH / 2)
BALLY = int(SCREEN_HEIGHT / 2)
RADIUS = 12
BALL_VELOCITY = 5

